// PlantTracker system test
describe('PlantTracker system test', () => {
    it('successfully signs up a new user', () => {
        function alertHandler(text) {
            expect(text).to.contain('User created successfully');
            cy.off('window:alert', alertHandler);
        }
        cy.visit('localhost:4000')
        cy.get('.btn-secondary').contains('Sign Up').click()
        cy.wait(500)
        cy.get('#signUpEmail').type('helena.segedin@gmail.com')
        cy.get('#signUpPassword').type('testpassword')
        cy.get('.modal-footer button').contains('Sign Up').click()
        cy.wait(1000)
        cy.on('window:alert', alertHandler)
        cy.get('button').contains('Sign In').click()
        cy.wait(500)
        cy.get('#signInEmail').type('helena.segedin@gmail.com')
        cy.get('#signInPassword').type('testpassword')
        cy.get('.modal-footer button').contains('Sign in').click()
        cy.wait(500)
        cy.get('button').should('contain', 'Sign Out')
        cy.get('button').should('contain', 'Add Plant')
        cy.get('button').contains('Add Plant').click()
        cy.wait(500)
        cy.get('#addPlantName').type('Test Plant')
        cy.get('#addPlantDescription').type('Test Description')
        cy.get('.modal-footer button').contains('Add Plant').click()
        cy.wait(500)
        cy.get('.plant-card').should('contain', 'Test Plant')
        cy.contains('.plant-card', 'Test Plant')
            .within(() => {
                cy.get('button').contains('Edit').click()
            })
        cy.wait(500)
        cy.get('#editPlantName').clear().type('Edited Plant')
        cy.get('#editPlantDescription').clear().type('Edited Description')
        cy.get('.modal-footer button').contains('Edit Plant').click()
        cy.wait(500)
        cy.get('.plant-card').should('contain', 'Edited Plant')
        cy.contains('.plant-card', 'Edited Plant')
            .within(() => {
                cy.get('.btn-close').click()
            })
        cy.wait(500)
        cy.get('button').contains('Delete').click()
        cy.wait(500)
        cy.get('button').should('not.contain', 'Edited Plant')
        cy.get('button').contains('Sign Out').click()
        cy.wait(500)
        cy.get('button').should('contain', 'Sign In')
        cy.get('button').should('contain', 'Sign Up')
    })
})
